### ISSUE TITLE
Obscure error when transferring files to provider

### ISSUE THREAD

**Issue by cryptobench** [cryptobench/golem-feedback#1]
When uploading a file to the provider via `script.upload_file(f"/app/var/media/nginx/{nginx_config}", f"/etc/nginx/conf.d/{nginx_config}")` , you often run into the error `send failed because receiver is gone` and then the whole agreement is terminated, and you're just left wondering what happened?

I don't even know what the issue is here or how to solve. Now I must spend a lot of time doing random debugging to just get an idea of what the issue **could be**

`[2022-11-11T14:48:52.027+0000 WARNING yapapi.services.service_runner] Unhandled exception in serviceTraceback (most recent call last):  File "/usr/local/lib/python3.8/site-packages/yapapi/services/service_runner.py", line 268, in _run_instance    batch = batch_task.result()  File "/proxy-example.py", line 205, in start    yield script  File "/usr/local/lib/python3.8/site-packages/yapapi/services/service_runner.py", line 284, in _run_instance    fut_result = yield batch  File "/usr/local/lib/python3.8/site-packages/yapapi/engine.py", line 720, in process_batches    results = await get_batch_results()  File "/usr/local/lib/python3.8/site-packages/yapapi/engine.py", line 701, in get_batch_results    event = script.process_batch_event(event_class, event_kwargs)  File "/usr/local/lib/python3.8/site-packages/yapapi/script/__init__.py", line 95, in process_batch_event    raise CommandExecutionError(str(command), event.message, event.stderr)yapapi.rest.activity.CommandExecutionError: Command 'SendFile dst=/etc/nginx/conf.d/9e454b95-71ae-4098-9851-0ca6a53994a7.conf src=/app/var/media/nginx/9e454b95-71ae-4098-9851-0ca6a53994a7.conf' failed on provider; message: 'Local service error: Transfer error: Send error: send failed because receiver is gone'`

**Comment by cryptobench** [comment]
This has been solved now, but this was happening because I was not uploading the file to a defined VOLUME on the provider machine. This really needs be clear by the error command.
